//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Controle_Financeiros = new HashSet<Controle_Financeiros>();
            this.Ordem_Servico = new HashSet<Ordem_Servico>();
        }
    
        public int cli_codigo { get; set; }
        public string cli_nome { get; set; }
        public string cli_telefone { get; set; }
        public string cli_cpf { get; set; }
        public string cli_cnpj { get; set; }
        public string cli_endereco { get; set; }
        public string cli_numerorua { get; set; }
        public string cli_cidade { get; set; }
        public string cli_bairro { get; set; }
        public string cli_cep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Controle_Financeiros> Controle_Financeiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordem_Servico> Ordem_Servico { get; set; }
    }
}
