//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controle_Financeiros
    {
        public int fin_codigos { get; set; }
        public Nullable<System.DateTime> fin_datadevencimento { get; set; }
        public Nullable<decimal> fin_valortotal { get; set; }
        public string fin_statu { get; set; }
        public Nullable<int> cod_clientes { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
