//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public int for_codigo { get; set; }
        public string for_racaosociais { get; set; }
        public string for_cnpj { get; set; }
        public string for_cpf { get; set; }
        public string for_endereco { get; set; }
        public string for_email { get; set; }
        public string for_telefone { get; set; }
    }
}
