//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int fun_codigos { get; set; }
        public string fun_nome { get; set; }
        public string fun_telefone { get; set; }
        public string fun_cpf { get; set; }
        public string fun_endereco { get; set; }
        public string fun_cidade { get; set; }
        public string fun_bairro { get; set; }
        public string fun_email { get; set; }
        public string fun_cargo { get; set; }
        public Nullable<decimal> fun_salario { get; set; }
        public string fun_cep { get; set; }
        public string fun_numero { get; set; }
    }
}
