//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordem_Servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordem_Servico()
        {
            this.Pecas = new HashSet<Pecas>();
        }
    
        public int ord_codigo { get; set; }
        public Nullable<System.DateTime> ord_dataderecebimento { get; set; }
        public Nullable<System.DateTime> ord_dataentrega { get; set; }
        public Nullable<int> ord_quantidade { get; set; }
        public string ord_descricao { get; set; }
        public Nullable<decimal> ord_valor { get; set; }
        public int cod_clientes { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pecas> Pecas { get; set; }
    }
}
