//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pecas
    {
        public int pec_codigos { get; set; }
        public string pec_nome { get; set; }
        public Nullable<int> cod_ordemservico { get; set; }
    
        public virtual Ordem_Servico Ordem_Servico { get; set; }
    }
}
